### ISSUE TITLE
Home assistant core

### ISSUE THREAD

**Issue by Puch-tdi** [ymartin59/spkrepo#2]
Hi, i'm terribly sorry but i don't know how i can reach you otherwise so i place my question in here.
Are you the same ymartin59 who made the home assistant core for synology devices?
If so, would you please contact me or make a repo where we can start a new thread?
The issue is the blockage of the user/owner sc-homeassistant. 
I installed it but cant do anything with it, i'm not allowed to make the "custom-component" folder or change my config file.
So other then the basic integrations are not allowed, this way is not much usefull.
I hope you are the wright person to talk to and hope to hear from you.
Thanks in advance,

Sander Ekeler
puchtdi@gmail.com

**Comment by ymartin59** [comment]
Hello. Please submit your request as new issue in this repository: https://github.com/SynoCommunity/spksrc/issues
@hgy59 will probably help you quicker than I may do.
